version: '3.8'
#ข้างบนคือ Version
#สำคัญ! การย่อหน้าต้องตรงกัน!

services: #Service คือส่วนที่ใช้จัดการ Contrainer #Link อธิบาย https://hub.docker.com/_/mysql
  db: #Service แรกชื่อ db เกี่ยวกับ databse
    image: mysql:8.0 # ปรับเป็น MySQL 8.0 เพื่อความทันสมัย (หรือใช้ 5.7 ตามเดิมได้หากต้องการ)
    container_name: mysql_db_821
    # MySQL 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งนี้เพื่อให้เข้ากับ Client รุ่นเก่าได้ดีขึ้น
    command: --default-authentication-plugin=mysql_native_password #สั่งให้ authentication ไปเลย
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8821:3306"
    volumes: #สรุปง่ายๆคือพื้นที่จัดเก็บของข้อมูล
      - mysql_data_821:/var/lib/mysql
    networks:
      - weblab821
    restart: always

  phpmyadmin: #Service ที่สอง phpmyadmin คือตัวเข้าสู่ฐานข้อมูล (Tools ที่ใช้เข้าถึงฐานข้อมูลมีหลายตัว) #Link อธิบาย https://hub.docker.com/_/phpmyadmin
    image: phpmyadmin:latest
    container_name: phpmyadmin_821
    environment:
      PMA_HOST: db # ใช้ชื่อ Service "db" แทนชื่อ Container เพื่อความยืดหยุ่นในระบบ Network
      PMA_PORT: 3306 #MySQL port defualt คือ 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M # เพิ่มลิมิตการอัปโหลดไฟล์ SQL
    ports:
      - "8822:80"
    depends_on: #คือ ทำ contrainer db ให้เสร็จก่อน
      - db
    networks:
      - weblab821
    restart: always #ในกรณีที่มีปัญหา

networks: #Service networks (การ Create)
  weblab821:
   driver: bridge #อยู่ใน network เดียวกันไม่ใช่ ip จริงๆ

volumes: #Service volumes (การ Create)
  mysql_data_821:
    driver: local 